name: Build Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "40 3 * * 1,4"

jobs:
  build:
    if: github.event_name == 'push'
    name: Build and publish
    strategy:
      matrix:
        version:
          - 15.4-alpine3.18
          - 15.3-alpine3.18
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Registry auth
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.version }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: |
            POSTGRES_VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_latest:
    if: github.event_name == 'schedule'
    name: Build `latest` tags
    strategy:
      matrix:
        version:
          - alpine
          - 15-alpine
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Registry auth
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ matrix.version }}

      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: |
            POSTGRES_VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
